sudo: false
language: rust
rust:
- stable
- beta
env:
  global:
  - RUST_BACKTRACE=1
  - PKGNAME=twig
  - LOCAL="~/.local"
  # encrypted github token for doc+coveralls upload
  - secure: "Pg4GNkTJsTB1AuI/KBQt8P6FF+HK1dgmwu2XHa/uhiBthDCAi82w3ZBzElWFdPM/HTWrW7q+7YZbB+zgY9LBs/DVb3HYa+j/hlIb9PmazEcZdrj4QDHcaA+Jak3cGhVejUu9zDyEYpPcFtCFeP/K63GyKED+LKWiRdFOioieX6d0rqi93pE+/0Dk1z8Sqq4G5G5Eu5L08DGU+FJrHYSG9N8/TgBMhkdhaRGKyWbShqzJQYv3krt4KF0xLS41kTkCdIsqeVD6owAWhpHKjUpzsn/gjXjH5pbX1f4dGEfd5cSXqAleE9CHRw/HYEsl+Q9Dk8XhkMu8VnsbkZCleReDl/a1/7NHGgn1iZfQhu5NhTcMe0PpNcPA9LWBsWKjbEca1xRMbJt8qQUjPf6smxV9LDxuPF7w8S8HhKoJv3gHE5s0cIf3oAxMSa1GUgw7klBPTTRhbrJTi2O3jEdgt5IatK3YW/a7njB95uafjtyeQCxxWrZ4D2R0UNhSkyp8cEM8KSEfI8AGIctYADmvbmKGIp0ksr8aN2GWWNPw3XruFpU8D8jDGvuRRyG1FTlhogfrBTs7fR6rq3Ui4vkRKCmrJpde1B/QKBw+rslJuMXPMHs9v8spKqEL0xpF0JqpbtGuAZvomyy2gXLQnAJ6mqhnzxP1ZXNDfj4FccoWowUDSpM="
addons:
  apt:
    packages:
    # travis-cargo dependencies
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
before_script: |
  # load travis cargo
  # - https://github.com/huonw/travis-cargo
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$LOCAL/bin:$PATH
script: |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
after_success: |
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  travis-cargo --only stable doc-upload 2> /dev/null # anti-credential leakage

  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  travis-cargo coveralls --no-sudo --verify 2> /dev/null # anti-credential leakage
