sudo: false
language: rust
rust:
- stable
- beta
env:
  global:
  - RUST_BACKTRACE=1
  # encrypted github token for doc+coveralls upload
  - secure: "K6yfXslYKoELg7DgLleLOdfEjOmblLZlxUQXtHD4Vx6PKR+hFm3t+XS8KxjXDrPf/Hop/GYgh5S67GSmjvgtu3dMD+M6moaFocRP5MAxc5jM1tCY5TRdRYDbCAMuN4kj8kzOHTbctMHpM0FMSnvdPkcCXfuMIOuO3Vt3J4f5llE8FQI54h+8qoYeE3SZnVQ4a6IXHPS6tLBpowdQB3D8pf44g5nNpHDd7kkOs3VlE0lPX1ENQXp6WGPmFpWPXwfY9xOebZDkJ0EZxGLUC9JF81mwPKxEQ+t7EecXx2saNQgggSxyc5lLVX628kj3Fnlkn/jw5pxIuWPRuQ3v8/CFXV+wD5LVVfpv15DluMz3zxw8MRLC7OmMrsnW+ws16Kj7gaRJ966Q1QJX286Lq1IN0MG5e+BqLeibCEVPVCFeaxH0u47ULFSTsNRu0ognaS60smnvkM2iKMNndaob/4fMo+p5bKFEyKre0N52IqiM18IlWzmtfupoK8nRIP46RI34ghRP9NBVJRQtHD+4pE8MAcSJqZAkFjur3sfRkLy1oY0QyZzTb7b1D25REvjKDXJcDmBwmeSoJ+i4F0cTGUhg8DNZATtQ1FTZWtwSCFyNjYnW4jK/Q4i0aStblIlh9BLLXncJX5aVKDrMb+nSGrvmn8g34HLl5xOEWsfVB4IkuUQ="
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
before_script: |
  # load travis cargo
  # - https://github.com/huonw/travis-cargo
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$LOCAL/bin:$PATH
script: |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
after_success: |
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  travis-cargo --only stable doc-upload 2> /dev/null # anti-credential leakage

  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  travis-cargo coveralls --no-sudo --verify 2> /dev/null # anti-credential leakage
